import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const PI_TOOL_NAMES = [
  "autocontext_solve_scenario",
  "autocontext_export_package",
  "autocontext_import_package",
  "autocontext_run_status",
] as const;

export interface PiPackage {
  packageDirName: string;
  files: Record<string, string>;
}

export interface WrittenPiPackage {
  outputDir: string;
  files: string[];
}

function stringValue(pkg: Record<string, unknown>, key: string): string {
  return typeof pkg[key] === "string" ? pkg[key] : "";
}

function stringArray(pkg: Record<string, unknown>, key: string): string[] {
  const raw = pkg[key];
  return Array.isArray(raw) ? raw.filter((value): value is string => typeof value === "string") : [];
}

function recordValue(pkg: Record<string, unknown>, key: string): Record<string, unknown> | null {
  const raw = pkg[key];
  return raw && typeof raw === "object" && !Array.isArray(raw)
    ? (raw as Record<string, unknown>)
    : null;
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "autocontext";
}

function description(pkg: Record<string, unknown>): string {
  const scenarioName = stringValue(pkg, "scenario_name");
  return (
    stringValue(pkg, "description").trim() ||
    `Autocontext package for ${stringValue(pkg, "display_name") || scenarioName}`
  );
}

function renderPrompt(pkg: Record<string, unknown>): string {
  const scenarioName = stringValue(pkg, "scenario_name");
  const title = stringValue(pkg, "display_name") || scenarioName.replace(/_/g, " ");
  const parts = [
    `# ${title}`,
    "",
    description(pkg),
    "",
    "Use this Pi package as a lean autocontext operating context.",
    "",
    "## Autocontext Tools",
    "",
    ...PI_TOOL_NAMES.map((tool) => `- \`${tool}\``),
  ];
  const optionalSections: Array<[string, string]> = [
    ["Task", stringValue(pkg, "task_prompt")],
    ["Evaluation Criteria", stringValue(pkg, "judge_rubric")],
    ["Playbook", stringValue(pkg, "playbook")],
  ];
  for (const [heading, content] of optionalSections) {
    if (content) parts.push("", `## ${heading}`, "", content);
  }
  const lessons = stringArray(pkg, "lessons");
  if (lessons.length > 0) {
    parts.push("", "## Lessons", "", ...lessons.map((lesson) => `- ${lesson}`));
  }
  const bestStrategy = recordValue(pkg, "best_strategy");
  if (bestStrategy) {
    parts.push(
      "",
      "## Best Known Strategy",
      "",
      "```json",
      JSON.stringify(bestStrategy, null, 2),
      "```",
    );
  }
  return parts.join("\n");
}

function renderReadme(pkg: Record<string, unknown>, scenarioSlug: string): string {
  const scenarioName = stringValue(pkg, "scenario_name");
  const title = stringValue(pkg, "display_name") || scenarioName.replace(/_/g, " ");
  return [
    `# ${title} Pi Package`,
    "",
    description(pkg),
    "",
    "This package was generated by autocontext for local Pi package installation.",
    "",
    "## Contents",
    "",
    `- \`skills/${scenarioSlug}-knowledge/SKILL.md\``,
    `- \`prompts/${scenarioSlug}.md\``,
    "- `autocontext.package.json`",
    "",
    "The strategy package can be re-imported with `autocontext_import_package`.",
  ].join("\n");
}

export function buildPiPackage(
  pkg: Record<string, unknown>,
  packageVersion: string,
): PiPackage {
  const scenarioName = stringValue(pkg, "scenario_name");
  if (!scenarioName) {
    throw new Error("Exported strategy package is missing scenario_name");
  }
  const scenarioSlug = slug(scenarioName);
  const skillPath = `skills/${scenarioSlug}-knowledge/SKILL.md`;
  const promptPath = `prompts/${scenarioSlug}.md`;
  const metadata = recordValue(pkg, "metadata");
  const metadataVersion = metadata && typeof metadata.mts_version === "string"
    ? metadata.mts_version.trim()
    : "";
  const manifest = {
    name: `autocontext-${scenarioSlug}-pi-package`,
    version: metadataVersion || packageVersion,
    private: true,
    description: description(pkg).slice(0, 200),
    files: ["README.md", "autocontext.package.json", "prompts", "skills"],
    pi: { skills: [skillPath], prompts: [promptPath], extensions: [], themes: [] },
    autocontext: {
      format: "pi-package",
      scenario_name: scenarioName,
      strategy_package: "autocontext.package.json",
      tools: [...PI_TOOL_NAMES],
    },
  };
  const skillMarkdown = stringValue(pkg, "skill_markdown");
  if (!skillMarkdown) {
    throw new Error("Exported strategy package is missing skill_markdown");
  }
  const entries: Array<[string, string]> = [
    ["README.md", renderReadme(pkg, scenarioSlug)],
    ["autocontext.package.json", JSON.stringify(pkg, null, 2)],
    ["package.json", JSON.stringify(manifest, null, 2)],
    [promptPath, renderPrompt(pkg)],
    [skillPath, skillMarkdown],
  ];
  return {
    packageDirName: `${scenarioSlug}-pi-package`,
    files: Object.fromEntries(entries.sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0)),
  };
}

export function defaultPiPackageOutputDir(scenarioName: string): string {
  return `${slug(scenarioName)}-pi-package`;
}

export function writePiPackage(pkg: PiPackage, outputDir: string): WrittenPiPackage {
  const files: string[] = [];
  for (const [relativePath, content] of Object.entries(pkg.files)) {
    const path = join(outputDir, relativePath);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${content.trimEnd()}\n`, "utf-8");
    files.push(path);
  }
  return { outputDir, files };
}
