/**
 * Server module — WebSocket protocol + run management (AC-347).
 */

export {
  PROTOCOL_VERSION,
  TRANSCRIPT_PROTOCOL_VERSION,
  BASE_SERVER_CAPABILITIES,
  SERVER_CAPABILITIES,
  TRANSCRIPT_SERVER_CAPABILITIES,
  STRUCTURED_TASK_CREATION_CAPABILITY,
  AGENT_TASK_OUTCOME_CAPABILITY,
  AGENT_TASK_OUTCOME_SCHEMA_VERSION,
  AgentTaskOutcomeGenerationV1Schema,
  AgentTaskOutcomeReceiptV1Schema,
  AgentTaskOutcomeV1Schema,
  AgentTaskTerminationReasonSchema,
  agentTaskOutcomeReceiptV1,
  AGENT_PROGRESS_NOTE_CAPABILITY,
  AGENT_PROGRESS_NOTE_EVENT_NAME,
  AgentProgressNoteEvidenceTargetSchema,
  AgentProgressNoteKindSchema,
  AgentProgressNotePayloadSchema,
  MAX_AGENT_PROGRESS_NOTE_EVIDENCE_TARGETS,
  MAX_AGENT_PROGRESS_NOTE_ID_LENGTH,
  MAX_AGENT_PROGRESS_NOTE_TEXT_LENGTH,
  MAX_RETAINED_AGENT_PROGRESS_NOTE_BYTES,
  AGENT_TASK_PLAN_CAPABILITY,
  AGENT_TASK_PLAN_EVENT_NAME,
  AgentTaskPlanIdSchema,
  AgentTaskPlanPayloadSchema,
  AgentTaskPlanStepSchema,
  AgentTaskPlanStepStatusSchema,
  HelloMsgSchema,
  EventMsgSchema,
  StateMsgSchema,
  ChatResponseMsgSchema,
  EnvironmentsMsgSchema,
  RunAcceptedMsgSchema,
  AckMsgSchema,
  ErrorMsgSchema,
  ScenarioGeneratingMsgSchema,
  ScenarioPreviewMsgSchema,
  ScenarioReadyMsgSchema,
  ScenarioErrorMsgSchema,
  MonitorAlertMsgSchema,
  PauseCmdSchema,
  ResumeCmdSchema,
  StopCmdSchema,
  InjectHintCmdSchema,
  OverrideGateCmdSchema,
  ChatAgentCmdSchema,
  StartRunCmdSchema,
  ResumeRunCmdSchema,
  ListScenariosCmdSchema,
  CreateScenarioCmdSchema,
  CreateTaskCmdSchema,
  ConfirmScenarioCmdSchema,
  ReviseScenarioCmdSchema,
  CancelScenarioCmdSchema,
  LoginCmdSchema,
  LogoutCmdSchema,
  SwitchProviderCmdSchema,
  WhoamiCmdSchema,
  AuthStatusMsgSchema,
  ServerMessageSchema,
  ClientMessageSchema,
  parseClientMessage,
  parseServerMessage,
} from "./protocol.js";
export type {
  AgentTaskOutcomeGenerationV1,
  AgentTaskOutcomeReceiptV1,
  AgentTaskOutcomeV1,
  AgentTaskTerminationReason,
  AgentProgressNoteEvidenceTarget,
  AgentProgressNoteKind,
  AgentProgressNotePayload,
  AgentTaskPlanPayload,
  AgentTaskPlanStep,
  AgentTaskPlanStepStatus,
  ServerMessage,
  ClientMessage,
} from "./protocol.js";

export {
  handleTuiLogin,
  handleTuiLogout,
  handleTuiSwitchProvider,
  handleTuiWhoami,
} from "./tui-auth.js";
export type { TuiLoginResult, TuiAuthStatus } from "./tui-auth.js";

export { RunManager } from "./run-manager.js";
export type { RunManagerOpts, EnvironmentInfo, RunManagerState } from "./run-manager.js";

export { InteractiveServer } from "./ws-server.js";
export type { InteractiveServerOpts } from "./ws-server.js";
