export const packageRole = "control";
export const packageTopologyVersion = 1;

export type {
	AgentsStartedPayload,
	GateDecidedPayload,
	GenerationCompletedPayload,
	GenerationStartedPayload,
	RunCompletedPayload,
	RunFailedPayload,
	RunStartedPayload,
	TournamentCompletedPayload,
} from "../../../../ts/src/loop/generation-event-coordinator.js";
export type { RoleCompletedPayload } from "../../../../ts/src/loop/generation-side-effect-coordinator.js";
export type { TournamentStartedPayload } from "../../../../ts/src/loop/generation-tournament-event-sequencing.js";
export type { StagnationReport } from "../../../../ts/src/loop/stagnation.js";
export type {
	AppId,
	ContentHash,
	EnvironmentTag,
	FeedbackRefId,
	ProductionTraceId,
	Scenario,
	SessionIdHash,
	UserIdHash,
} from "../../../../ts/src/production-traces/contract/branded-ids.js";
export type {
	DetectedBy,
	EnvContext,
	FeedbackKind,
	FeedbackRef,
	MessageRole,
	ModelRoutingDecisionReason,
	ModelRoutingFallbackReason,
	OutcomeLabel,
	ProductionOutcome,
	ProductionTrace,
	ProductionTraceRouting,
	ProductionTraceSchemaVersion,
	ProviderInfo,
	ProviderName,
	RedactionMarker,
	RedactionReason,
	SessionIdentifier,
	TimingInfo,
	ToolCall,
	TraceLinks,
	TraceMessage,
	TraceSource,
	UsageInfo,
	ValidationResult,
} from "../../../../ts/src/production-traces/contract/types.js";
export { PRODUCTION_TRACE_SCHEMA_VERSION } from "../../../../ts/src/production-traces/contract/types.js";
export { ResearchBrief } from "../../../../ts/src/research/consultation.js";
export type { ResearchAdapter } from "../../../../ts/src/research/types.js";
export {
	Citation,
	ResearchConfig,
	ResearchQuery,
	ResearchResult,
	Urgency,
} from "../../../../ts/src/research/types.js";
export {
	AckMsgSchema,
	AuthStatusMsgSchema,
	CancelScenarioCmdSchema,
	ChatAgentCmdSchema,
	ChatResponseMsgSchema,
	ConfirmScenarioCmdSchema,
	CreateScenarioCmdSchema,
	EnvironmentsMsgSchema,
	ErrorMsgSchema,
	EventMsgSchema,
	ExecutorInfoSchema,
	ExecutorResourcesSchema,
	HelloMsgSchema,
	InjectHintCmdSchema,
	ListScenariosCmdSchema,
	LoginCmdSchema,
	LogoutCmdSchema,
	MissionProgressMsgSchema,
	MonitorAlertMsgSchema,
	OverrideGateCmdSchema,
	PauseCmdSchema,
	PROTOCOL_VERSION,
	ResumeCmdSchema,
	ReviseScenarioCmdSchema,
	RunAcceptedMsgSchema,
	ScenarioErrorMsgSchema,
	ScenarioGeneratingMsgSchema,
	ScenarioInfoSchema,
	ScenarioPreviewMsgSchema,
	ScenarioReadyMsgSchema,
	ScoringComponentSchema,
	StartRunCmdSchema,
	StateMsgSchema,
	StrategyParamSchema,
	SwitchProviderCmdSchema,
	WhoamiCmdSchema,
} from "../../../../ts/src/server/protocol.js";
