/**
 * AC-937: the TypeScript extractor must agree with the Python one, case by case.
 *
 * `docs/model-json-extraction-parity-fixtures.json` is GENERATED by running
 * Python's `extract_json` over a corpus organised by the rule each case
 * exercises. This file replays it. Neither side hand-writes the expected
 * values, so a divergence shows up as a failing case rather than as two
 * implementations that were each individually plausible.
 *
 * Outcomes compare status and, for failures, only that the call failed the same
 * WAY (raised vs returned null) -- not the message. Python and JavaScript word
 * parse errors differently, and pinning wording would fail on a difference
 * nobody cares about while hiding the ones that matter.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { extractJson, type ExtractJsonOptions } from "../src/execution/model-json.js";

type Expected =
  | { status: "ok"; value: Record<string, unknown> }
  | { status: "none" }
  | { status: "raised"; error_type: string };

interface Case {
  text: string;
  options: { on_failure?: "raise" | "none"; require_unique?: boolean };
  expected: Expected;
}

const FIXTURE_PATH = join(
  import.meta.dirname,
  "..",
  "..",
  "docs",
  "model-json-extraction-parity-fixtures.json",
);

const FIXTURE = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as {
  groups: Record<string, Record<string, Case>>;
};

function toOptions(raw: Case["options"]): ExtractJsonOptions {
  return {
    ...(raw.on_failure ? { onFailure: raw.on_failure } : {}),
    ...(raw.require_unique ? { requireUnique: raw.require_unique } : {}),
  };
}

describe("model-JSON extraction parity with Python", () => {
  for (const [group, cases] of Object.entries(FIXTURE.groups)) {
    describe(group, () => {
      for (const [name, testCase] of Object.entries(cases)) {
        it(`matches Python for ${name}`, () => {
          const run = () => extractJson(testCase.text, toOptions(testCase.options));

          if (testCase.expected.status === "raised") {
            expect(run).toThrow();
            return;
          }
          if (testCase.expected.status === "none") {
            expect(run()).toBeNull();
            return;
          }
          expect(run()).toEqual(testCase.expected.value);
        });
      }
    });
  }

  it("replays every recorded case", () => {
    // A fixture that silently stopped being read would pass every assertion
    // above by having none to make.
    const total = Object.values(FIXTURE.groups).reduce(
      (sum, cases) => sum + Object.keys(cases).length,
      0,
    );
    expect(total).toBeGreaterThanOrEqual(39);
  });
});
