"""Correctness-first recursive optimization for externally benchmarked kernels."""

from autocontext.kernel_evolution.benchmark import (
    ExternalKernelBenchmarkRunner,
    KernelBenchmarkEvaluator,
    KernelBenchmarkEvaluatorConfig,
    KernelBenchmarkExecution,
    KernelBenchmarkRunner,
)
from autocontext.kernel_evolution.docker_worker import (
    DockerGPUDeviceGrant,
    DockerKernelBenchmarkRunner,
    DockerKernelWorkerLimits,
)
from autocontext.kernel_evolution.lineage import KernelLineageStore
from autocontext.kernel_evolution.models import (
    ARTIFACT_IDENTITY_VERSION,
    PROTOCOL_COMPATIBILITY_VERSION,
    SCHEMA_VERSION,
    KernelAttemptRecord,
    KernelBenchmarkObservation,
    KernelBenchmarkProtocol,
    KernelBenchmarkReport,
    KernelCandidate,
    KernelCompileReport,
    KernelCorrectnessReport,
    KernelEvolutionResult,
    KernelHardwareIdentity,
    KernelPerformanceReport,
    KernelPromotionGateResult,
    KernelResourceReport,
    KernelTimingBlock,
    artifact_digest,
    artifact_digest_from_source_digest,
    canonical_digest,
    content_digest,
)
from autocontext.kernel_evolution.runner import (
    KernelBaselineError,
    KernelConfirmationFn,
    KernelEvolutionConfig,
    KernelEvolutionRunner,
    KernelIntegrityError,
    KernelPromotionPolicy,
)

__all__ = [
    "ARTIFACT_IDENTITY_VERSION",
    "PROTOCOL_COMPATIBILITY_VERSION",
    "SCHEMA_VERSION",
    "ExternalKernelBenchmarkRunner",
    "DockerGPUDeviceGrant",
    "DockerKernelBenchmarkRunner",
    "DockerKernelWorkerLimits",
    "KernelAttemptRecord",
    "KernelBaselineError",
    "KernelBenchmarkEvaluator",
    "KernelBenchmarkEvaluatorConfig",
    "KernelBenchmarkExecution",
    "KernelBenchmarkObservation",
    "KernelBenchmarkProtocol",
    "KernelBenchmarkReport",
    "KernelBenchmarkRunner",
    "KernelCandidate",
    "KernelConfirmationFn",
    "KernelCompileReport",
    "KernelCorrectnessReport",
    "KernelEvolutionConfig",
    "KernelEvolutionResult",
    "KernelEvolutionRunner",
    "KernelHardwareIdentity",
    "KernelIntegrityError",
    "KernelLineageStore",
    "KernelPerformanceReport",
    "KernelPromotionGateResult",
    "KernelPromotionPolicy",
    "KernelResourceReport",
    "KernelTimingBlock",
    "artifact_digest",
    "artifact_digest_from_source_digest",
    "canonical_digest",
    "content_digest",
]
